check_install delta
if check_install git; then
	alias g='git'
	alias ga='git add'
	alias gap='ga -p'
	alias gA='ga -A'
	alias gAcanepf='gA && gcane && gpf'
	alias gAcapf='gA && gca && gpf'
	alias gb='g branch'
	alias gbm='gb -m'
	alias gc='g commit'
	alias gca='gc --amend'
	alias gcane='gca --no-edit'
	alias gcapf='gca && gpf'
	alias gcl='g clone'
	alias gcm='gc -m'
	alias gcp='gc && gp'
	alias gcpf='gc && gpf'
	alias gd='g diff --color=always'
	alias gdh='gd HEAD'
	alias gf='g fetch'
	alias gfr='gf && gr'
	alias gl='g log --show-signature'
	alias gm='g merge'
	alias gma='gm --abort'
	alias gmc='gm --continue'
	alias gp='g push'
	alias gpf='gp --force-with-lease'
	alias gr='g rebase'
	alias gra='gr --abort'
	alias grc='gr --continue'
	alias gri='gr -i'
	alias grest='g restore'
	alias grst='g reset'
	alias gs='g status'
	alias gst='g stash'
	alias gstp='gst pop'
	alias gsh='g show'
	alias gsw='g switch'
	alias gswc='gfr;gsw -c'
	alias gu='ga -u'
fi
