'$schema' = 'https://starship.rs/config-schema.json'

palette = 'catppuccin_macchiato'

format = '''
$username$java$nodejs$fill$memory_usage$kubernetes
$git_state$git_branch $git_commit$git_status$fill$time $battery
$directory $character
'''

[character]
success_symbol = '[❯](green)'
error_symbol = '[❯](red)'
vimcmd_symbol = '[❮](yellow)'

[directory]
format = '[$read_only]($read_only_style)󰉋 [$path]($style)'
home_symbol = ''
read_only = ' '
truncation_length = 4
truncate_to_repo = true
truncation_symbol = '󰇘/'
style = 'bold lavender'

[username]
style_user = 'green'
style_root = 'bold red'
format = '[ $user]($style) '
disabled = false
show_always = true

[fill]
style = 'bold surface0'

[line_break]
disabled = true

[time]
disabled = false
time_format = '%F %T'
format = ' [ $time]($style)'
style = 'bold text'

[git_branch]
format = '[$symbol$branch(:$remote_branch)]($style)'

[git_commit]
tag_disabled = false
tag_symbol = '  '

[git_metrics]
disabled = false

[git_status]
disabled = false
format = '$stashed$conflicted$ahead_behind$staged$modified$renamed$deleted$untracked'
stashed = '[*$count](lavender) '
conflicted = '[󰡌 $count](red) '
ahead = '[⇡$count](yellow) '
diverged = '[⇕⇡$ahead_count⇣$behind_count](yellow) '
behind = '[⇣$count](yellow) '
staged = '[+$count](green) '
modified = '[!$count](peach) '
renamed = '[»$count](blue) '
deleted = '[✘$count](maroon) '
untracked = '[?$count](subtext0) '

[kubernetes]
disabled = false
symbol = '⎈ '
format = '[$symbol$context (\($namespace\))]($style)'

[memory_usage]
disabled = false
format = '[ ${ram} | 󰣁 ${swap}]($style) '
threshold = -1
symbol = ''
style = 'overlay0'

[java]
format = '[$symbol($version)]($style) '
version_format = 'v$raw'

[nodejs]
disabled = false
format = '[$symbol($version$engines_version)]($style) '
version_format = 'v$raw'

[battery]
disabled = false
format = '[$symbol$percentage]($style)'

[[battery.display]]
threshold = 10
charging_symbol = '󰢜 '
discharging_symbol = '󰁺 '
style = 'bold mauve'

[[battery.display]]
threshold = 20
charging_symbol = '󰂆 '
discharging_symbol = '󰁻 '
style = 'bold red'

[[battery.display]]
threshold = 30
charging_symbol = '󰂇 '
discharging_symbol = '󰁼 '
style = 'bold maroon'

[[battery.display]]
threshold = 40
charging_symbol = '󰂈 '
discharging_symbol = '󰁽 '
style = 'bold peach'

[[battery.display]]
threshold = 50
charging_symbol = '󰢝 '
discharging_symbol = '󰁾 '
style = 'bold yellow'

[[battery.display]]
threshold = 60
charging_symbol = '󰂉 '
discharging_symbol = '󰁿 '
style = 'bold green'

[[battery.display]]
threshold = 70
charging_symbol = '󰢞 '
discharging_symbol = '󰂀 '
style = 'bold teal'

[[battery.display]]
threshold = 80
charging_symbol = '󰂊 '
discharging_symbol = '󰂁 '
style = 'bold sky'

[[battery.display]]
threshold = 90
charging_symbol = '󰂋 '
discharging_symbol = '󰂂 '
style = 'bold sapphire'

[[battery.display]]
threshold = 100
charging_symbol = '󰂅 '
discharging_symbol = '󰁹 '
style = 'bold blue'

[palettes.catppuccin_macchiato]
rosewater = '#f4dbd6'
flamingo = '#f0c6c6'
pink = '#f5bde6'
mauve = '#c6a0f6'
red = '#ed8796'
maroon = '#ee99a0'
peach = '#f5a97f'
yellow = '#eed49f'
green = '#a6da95'
teal = '#8bd5ca'
sky = '#91d7e3'
sapphire = '#7dc4e4'
blue = '#8aadf4'
lavender = '#b7bdf8'
text = '#cad3f5'
subtext1 = '#b8c0e0'
subtext0 = '#a5adcb'
overlay2 = '#939ab7'
overlay1 = '#8087a2'
overlay0 = '#6e738d'
surface2 = '#5b6078'
surface1 = '#494d64'
surface0 = '#363a4f'
base = '#24273a'
mantle = '#1e2030'
crust = '#181926'

[palettes.catppuccin_latte]
rosewater = '#dc8a78'
flamingo = '#dd7878'
pink = '#ea76cb'
mauve = '#8839ef'
red = '#d20f39'
maroon = '#e64553'
peach = '#fe640b'
yellow = '#df8e1d'
green = '#40a02b'
teal = '#179299'
sky = '#04a5e5'
sapphire = '#209fb5'
blue = '#1e66f5'
lavender = '#7287fd'
text = '#4c4f69'
subtext1 = '#5c5f77'
subtext0 = '#6c6f85'
overlay2 = '#7c7f93'
overlay1 = '#8c8fa1'
overlay0 = '#9ca0b0'
surface2 = '#acb0be'
surface1 = '#bcc0cc'
surface0 = '#ccd0da'
base = '#eff1f5'
mantle = '#e6e9ef'
crust = '#dce0e8'
