import = [ "~/.config/alacritty/themes/catppuccin-macchiato.toml" ] # theme

[env]
TERM = "xterm-256color"

[window]
dimensions = { columns = 0, lines = 0 }
position = "None"
padding = { x = 0, y = 0 }
dynamic_padding = false
decorations = "None"
opacity = 1.0
blur = true
startup_mode = "Windowed"
title = "Alacritty"
dynamic_title = true
class = { instance = "Alacritty", general = "Alacritty" }
decorations_theme_variant = "None"

[scrolling]
history = 100000
multiplier = 3

[font]
normal = { family = "FiraCode Nerd Font Mono", style = "Regular"}

[bell]
animation = "Linear"
duration = 1
color = "#ed8796"
command = "None"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"
save_to_clipboard = false

[cursor]
style = { shape = "Block", blinking = "Never" }
vi_mode_style = "None"
blink_interval = 750
blink_timeout = 5
unfocused_hollow = true
thickness = 0.15

[terminal]
osc52 = "OnlyCopy"

[mouse]
hide_when_typing = true
bindings = []

[hints]
alphabet = "jfkdls;ahgurieowpq"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse = {  mods = "Control", enabled = true }
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[keyboard]

[debug]
render_timer = false
persistent_logging = false
log_level = "Warn"
renderer = "None"
print_events = false
highlight_damage = false
prefer_egl = false
